### PR TITLE
Better python bindings (classes, C++-like API, types enforcement)

### PR DESCRIPTION
**Pull request by roncapat**
Hello,
I'm a Computer Engineering student a the University of Genoa (Italy). I'm currently working with my colleagues @lapo5 and @aled96 on a project that involves the use of some Dynamixels AX-12+/A, and we noticed that until now, Python support in this SDK is limited to exporting C API symbols, delegating the user to handle non-native parameter/return types. 

We'd love to enhance Python support by contributing upstream. 

Here are our proposals:
- use ctypes library to specify admitted parameter types and return types of the C API functions exposed
- use python class support to mimic the C++ API: same classes, same methods, almost the same prototypes (except for returning multiple values as tuple instead as by reference)
- use ctypes helpers to provide a native Python API: user will no more need to handle type conversions by hand; instead, the python class methods will hide the magic of the underlying C calls.

We'd like to know if you are interested in those patches, and have some feedback too. This is to be considered as a work in progress, since we are still testing our code in these days with our modded Bioloid with a Raspberry Pi backpack.

Documentation is missing right now, we should at least briefly explain expected args and types.

We plan to also extend Python support with an implementation of Dynamixel-Workbench too, for easy ROS integration, and we would be delighted to share the Python implementation when almost completed.

### CODE REVIEW

**Comment by ROBOTIS-Leon** [comment]
@roncapat 

Hi, 

thank you along with your colleagues, @lapo5 @aled96, for your invaluable contribution on Dynamixel SDK.

I think personally that your work is one of the featured subject which was taken into account but was not carried out. The problem I faced was, as you pointed out, non-native in python, and of course while the python API uses c dll, things can be going weird. So the python SDK should be once tried by pythoner.

Now, as we got the issue #122 from whom wants to make Python-as-a-native SDK by their hands, but facing serious issues while handling packet structures, kernels, etc., we decided to develop and release it. 

Today I will upload the SDK Python onto develop branch (I worked with this in my repository in a while) and will hold a beta test for few weeks. Handling non-native types of param/ret was fixed but followed the concepts of in/output as much as it can. 

I think that you're professional on either python or the system, so I hope you be a beta tester, and advise what you've been focusing on.

What do you think about

**Comment by roncapat** [comment]
We'll look into the version you're releasing and test it of course. By the
way, do you already have plans for Python support in dynamixel-workbench
too? And in that case, what's the status of the development?

>

**Comment by ROBOTIS-Leon** [comment]
@roncapat 

I just uploaded the source in develop branch DynamixelSDK/python/. Have a look, and tell me your thoughts. It is in python 2 / Ubuntu Linux as the development default... I'm going to extend it to the other OS, and python 3.

Workbench wise... @routiful has the key; we brang him into the conversation. 
First and foremost, the reason why we developed DynamixelSDK python in native language is to make pythoners-but-don't-know-much-about-cpp easily customize their framework. We will add current work into the official DynamixelSDK ROS package; so pythoners can use python codes as well as cppers can use cpp codes.

reply for EDIT: Yes, that's what I'm looking forward to be happened. Exactly saying, some returns are very weird from pythoners' view, you can join step by step, module by module, func by func. As long as it wouldn't be far from general API concepts in the other language SDKs, seriously considering, I will take it.

**Comment by ROBOTIS-Leon** [comment]
@roncapat 

after finishing short talk with @routiful, please join to the conversation #122. Another pythoners are having talk with python SDK. I will summarize every talks there, and will put the idea in the code or as well as get PR from them, or you.

**Comment by roncapat** [comment]
I suggest to keep a Python 2 version, because AFAIK ROS is not yet based on
Python 3 unfortunately. Today I'll start reviewing the code, maybe I'll
suggest some minor changes.

I'll join that discussion ASAP ;)

>

**Comment by ROBOTIS-Leon** [comment]
@roncapat 

I finished porting on Windows as well, and also it now works both version of python; there was a little bit modification, and hope that it won't affect to any ROS settings.

check it later

**Comment by routiful** [comment]
Hi :) @roncapat 

Unfortunately, we don't have any plan to support Python with Dynamixel-Workbench. 
I anticipate your Python implementation. If you have any idea while you develop it, please feel comfortable to open issue in [Dynamixel-Workbench repo](https://github.com/ROBOTIS-GIT/dynamixel-workbench/issues).

**Comment by roncapat** [comment]
Hi @routiful, a dynamixel-workbench implementation in Python will then be coming in the next weeks, when we plan to finish some tests ;)

**Comment by ROBOTIS-Leon** [comment]
@roncapat 

If you don't mind, I'll close this issue :D

**Pull request closed without merging**
